import os, json
from flask import Flask, request, jsonify, send_from_directory

app = Flask(__name__, static_folder='static', template_folder='templates')

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")

SYSTEM_PROMPT = """You are XeerHub AI, a legal information assistant specializing exclusively in the laws of the Federal Republic of Somalia.

You have deep knowledge of:
1. The Somalia Labour Code
2. The Companies Law (Law No. 18, signed 26 December 2019)
3. The Foreign Investment Law of the Federal Republic of Somalia
4. The Somali Civil Law and general civil code principles

STRICT RULES:
- Answer in plain English that a non-lawyer can understand
- Always cite the specific article number(s): e.g. "Labour Code · Art. 38"
- Keep answers under 160 words
- Never give a definitive legal opinion
- End every answer with: "For your specific situation, consult a qualified Somali lawyer."
- Never invent article numbers"""


QA_DATA = {

  "labor": [
    {"id":1,"q":"Do I have to give an employee a written contract?","a":"Yes. Every employment relationship must be documented in writing. Verbal agreements are not enforceable for key terms such as salary, duration, and job role. The contract must state the nature of work, location, compensation, and duration if fixed-term.","ref":"Labour Code · Arts. 16-18","tier":"free"},
    {"id":2,"q":"How many days of annual leave is an employee entitled to?","a":"An employee who has completed one full year of service is entitled to a minimum of 15 working days of paid annual leave. This increases with years of service. Leave cannot be replaced by a cash payment unless employment ends before the leave is taken.","ref":"Labour Code · Arts. 64-67","tier":"free"},
    {"id":3,"q":"Can I fire someone without giving a reason?","a":"No. Termination without just cause is unlawful. Valid reasons include serious misconduct, incapacity, or genuine operational need. You must give advance notice. The notice period depends on how long the employee has worked for you. Wrongful dismissal can result in compensation claims.","ref":"Labour Code · Arts. 38-45","tier":"free"},
    {"id":4,"q":"How much notice do I have to give before ending a contract?","a":"Notice periods are tied to length of service. Workers with less than one year require shorter notice; longer-tenured employees require more. During the notice period the employee must continue to receive their full salary. Either party can waive notice by paying compensation in lieu.","ref":"Labour Code · Arts. 40-42","tier":"free"},
    {"id":5,"q":"What is the maximum number of hours an employee can work per week?","a":"The standard working week is 48 hours. Any hours beyond this are overtime and must be compensated at a premium rate — typically 1.25x to 1.5x the normal hourly rate depending on whether overtime falls on a weekday, weekend, or public holiday.","ref":"Labour Code · Arts. 55-58","tier":"free"},
    {"id":6,"q":"Is maternity leave paid or unpaid?","a":"Female employees are entitled to paid maternity leave of 60 days. During this period the employee must receive her full salary and cannot be dismissed. Employers cannot count maternity leave as sick leave or deduct it from annual leave entitlement.","ref":"Labour Code · Arts. 72-75","tier":"free"},
    {"id":7,"q":"Can an employer reduce a worker salary without their agreement?","a":"No. A salary reduction requires the written consent of the employee. Imposing a pay cut unilaterally is treated as constructive dismissal, entitling the employee to claim wrongful termination compensation.","ref":"Labour Code · Arts. 20-22","tier":"free"},
    {"id":8,"q":"What happens if I do not pay wages on time?","a":"Delayed payment of wages is a violation of the Labour Code. The employer becomes liable for the unpaid amount plus potential penalties. Persistent non-payment gives the employee the right to consider themselves constructively dismissed and seek full severance entitlement.","ref":"Labour Code · Arts. 30-32","tier":"free"},
    {"id":9,"q":"Are NGO staff in Somalia protected by local labor law?","a":"Yes. Foreign and local NGOs operating in Somalia must comply with the Labour Code for all locally hired staff. International staff on international contracts may have different arrangements, but local hires are fully protected regardless of the employer nationality or status.","ref":"Labour Code · Arts. 3-5","tier":"free"},
    {"id":10,"q":"What severance is owed when a company closes down?","a":"When a business ceases operations, employees are entitled to severance pay based on their length of service, calculated as a multiple of monthly salary per year worked. All outstanding wages, leave balances, and entitlements must be settled before any assets are distributed.","ref":"Labour Code · Arts. 46-50","tier":"free"},
    {"id":11,"q":"Can an employee work for two employers at the same time?","a":"An employee may take on a second job but must not allow it to conflict with their primary employer interests. If the employment contract includes an exclusivity clause, working for another employer during working hours is a breach that can lead to disciplinary action or dismissal.","ref":"Labour Code · Arts. 18-20","tier":"premium"},
    {"id":12,"q":"What is the minimum wage in Somalia?","a":"The Labour Code provides for the establishment of a minimum wage but the specific amount is set by ministerial decree and may vary by sector. Employers must pay at least the applicable minimum wage for the sector their employees work in.","ref":"Labour Code · Art. 29","tier":"premium"},
    {"id":13,"q":"Can an employer make deductions from a worker salary?","a":"Deductions are only allowed in limited circumstances: repayment of an employer loan, overpayment of wages, or as ordered by a court. Total deductions in any month cannot reduce take-home pay below the minimum wage.","ref":"Labour Code · Arts. 31-33","tier":"premium"},
    {"id":14,"q":"What are the rules for probationary periods?","a":"Employers can set a probationary period at the start of employment during which either party can end the contract with shorter notice. The probationary period must be stated in the written contract and cannot be used repeatedly for the same employee in the same role.","ref":"Labour Code · Art. 17","tier":"premium"},
    {"id":15,"q":"Does an employee get paid for public holidays?","a":"Yes. Employees are entitled to paid leave on all officially declared public holidays. If required to work on a public holiday they must receive additional compensation — at least double their normal daily rate for that day.","ref":"Labour Code · Arts. 62-63","tier":"premium"},
    {"id":16,"q":"What counts as serious misconduct justifying immediate dismissal?","a":"Serious misconduct includes theft from the employer, violence or threats against colleagues, deliberate destruction of company property, serious breach of confidentiality, and repeated insubordination after formal warnings. Immediate dismissal without notice is only justified for the most serious offences.","ref":"Labour Code · Arts. 41-43","tier":"premium"},
    {"id":17,"q":"Can a fixed-term contract be renewed indefinitely?","a":"Fixed-term contracts can be renewed but if the same employee is kept on successive fixed-term contracts for a continuous period the law may treat the arrangement as a permanent open-ended contract. Employers cannot use repeated short-term contracts to avoid permanent employment obligations.","ref":"Labour Code · Arts. 16-17","tier":"premium"},
    {"id":18,"q":"What sick leave is an employee entitled to?","a":"Employees are entitled to paid sick leave when they produce a medical certificate from a recognised medical professional. The duration of paid sick leave and the transition to unpaid leave or termination on health grounds is governed by the Labour Code provisions on incapacity.","ref":"Labour Code · Arts. 68-71","tier":"premium"},
    {"id":19,"q":"Can a pregnant employee be dismissed?","a":"No. Dismissing an employee because of pregnancy or during maternity leave is unlawful. Any termination during pregnancy or within a protected period after birth is presumed to be discriminatory and the employer must prove a legitimate unrelated reason.","ref":"Labour Code · Arts. 72-76","tier":"premium"},
    {"id":20,"q":"What are the rules for night work?","a":"Employees required to work at night — typically between 10pm and 6am — are entitled to additional compensation above their normal hourly rate. Night work must be specified in the contract or agreed separately and workers must receive appropriate rest periods.","ref":"Labour Code · Arts. 56-58","tier":"premium"},
    {"id":21,"q":"Can an employer change an employee job without their consent?","a":"No. An employer cannot unilaterally change fundamental contract terms including job role, location, or hours without the employee written consent. Such a change without consent is treated as constructive dismissal giving rise to a compensation claim.","ref":"Labour Code · Arts. 20-22","tier":"premium"},
    {"id":22,"q":"Who handles labour disputes in Somalia?","a":"Labour disputes are first referred to the Ministry of Labour for conciliation and mediation. If not resolved, the dispute can be brought before courts with jurisdiction over employment matters. Both parties should document all communications throughout.","ref":"Labour Code · Arts. 85-92","tier":"premium"},
    {"id":23,"q":"Are employees entitled to a rest day every week?","a":"Yes. Every employee is entitled to at least one full rest day per week — typically Friday in Somalia. If required to work on their rest day they must receive compensatory time off or additional pay.","ref":"Labour Code · Art. 60","tier":"premium"},
    {"id":24,"q":"What records must an employer keep about their employees?","a":"Employers must maintain records of each employee personal details, contract terms, salary history, leave taken, disciplinary actions, and any changes to employment terms. These must be kept for a minimum period and be available for Ministry of Labour inspection.","ref":"Labour Code · Arts. 13-15","tier":"premium"},
    {"id":25,"q":"Can employees form or join a trade union?","a":"Yes. Employees have the right to form and join trade unions and engage in collective bargaining. Employers cannot penalise employees for union membership or activities. Collective agreements negotiated by unions are binding on all employees in the category they cover.","ref":"Labour Code · Arts. 93-100","tier":"premium"},
    {"id":26,"q":"What happens if an employee is injured at work?","a":"An employer is responsible for workplace safety and must compensate employees for injuries sustained in the course of their work. The employee is entitled to medical treatment costs, compensation for incapacity, and in fatal cases the employer owes compensation to the deceased dependants.","ref":"Labour Code · Arts. 77-84","tier":"premium"},
    {"id":27,"q":"What is the process for making an employee redundant?","a":"Redundancy requires genuine justification, advance notice to the employee, and payment of severance calculated by length of service. The employer must demonstrate that the redundancy is genuine and not a pretext for dismissal.","ref":"Labour Code · Arts. 44-50","tier":"premium"},
    {"id":28,"q":"Can an employer hire a child or young person?","a":"The Labour Code sets minimum working ages and restricts the type of work young people can perform. Children below the minimum age cannot be employed in any capacity. Young people above the minimum age can only work in permitted roles with reduced hours and additional protections.","ref":"Labour Code · Arts. 6-10","tier":"premium"},
    {"id":29,"q":"What is the difference between an employee and an independent contractor?","a":"An employee works under the direction and control of the employer with set hours and integrated into the organisation. An independent contractor works autonomously and takes on business risk. Labour Code protections apply to employees. Misclassifying an employee as a contractor is unlawful.","ref":"Labour Code · Arts. 3-5","tier":"premium"},
    {"id":30,"q":"What happens to employment contracts when a business is sold?","a":"When a business is sold or transferred as a going concern, employment contracts transfer automatically to the new owner on the same terms. The new employer cannot use the transfer as a reason to dismiss employees or worsen their terms of employment.","ref":"Labour Code · Arts. 51-54","tier":"premium"},
    {"id":31,"q":"Is an employer required to provide a payslip?","a":"Yes. Employers must provide employees with a written statement of their pay each time wages are paid. The payslip must show gross pay, any deductions and the reason for them, and the net amount paid to the employee.","ref":"Labour Code · Arts. 29-30","tier":"premium"},
    {"id":32,"q":"What protection exists against workplace harassment?","a":"Employees are entitled to work free from harassment and intimidation. Harassment by managers or colleagues can constitute grounds for constructive dismissal if the employer fails to address it. Employers are required to maintain a safe working environment including protection from psychological harm.","ref":"Labour Code · Arts. 77-84","tier":"premium"},
    {"id":33,"q":"What notice must an employee give when resigning?","a":"An employee wishing to resign must give notice to the employer. The required notice period mirrors the employer obligation and is tied to length of service. An employee who leaves without proper notice may be liable for compensation for losses caused by the sudden departure.","ref":"Labour Code · Arts. 40-42","tier":"premium"},
    {"id":34,"q":"Are part-time employees entitled to the same rights as full-time employees?","a":"Yes. Part-time employees have the same legal rights as full-time employees on a pro-rata basis. They are entitled to the same hourly rate, proportionate leave, and the same protections against unfair dismissal. Treating part-time workers less favourably is unlawful.","ref":"Labour Code · Arts. 3-5","tier":"premium"},
    {"id":35,"q":"Can an employer withhold a final salary payment after dismissal?","a":"No. An employer must pay all outstanding wages, accrued leave, and contractual entitlements at the time of termination or within a short period after. Withholding the final salary as leverage or punishment is unlawful and exposes the employer to a Ministry of Labour claim.","ref":"Labour Code · Arts. 29-32","tier":"premium"},
    {"id":36,"q":"What are the employer obligations during a disciplinary process?","a":"An employer conducting a disciplinary process must notify the employee of the allegations in writing, give a reasonable opportunity to respond, hold a fair hearing, and communicate the outcome in writing. Dismissal without following proper process is likely to be found unlawful.","ref":"Labour Code · Arts. 38-45","tier":"premium"},
    {"id":37,"q":"What is the rule on rest breaks during the working day?","a":"Employees working a full day are entitled to a rest break — typically at least 30 minutes — not counted as working time. During Ramadan, working hours are reduced for Muslim employees and rest break arrangements may be adjusted accordingly.","ref":"Labour Code · Arts. 59-61","tier":"premium"},
    {"id":38,"q":"Can an employer require employees to sign a non-compete agreement?","a":"Non-compete clauses can be included in employment contracts but must be reasonable in scope, geographic area, and duration. An overly broad restriction preventing an employee from earning a living in their profession after leaving is unlikely to be enforceable.","ref":"Labour Code · Arts. 18-20","tier":"premium"},
    {"id":39,"q":"Can an employer change the workplace location without consent?","a":"Changing an employee place of work is a change to a fundamental contract term and generally requires agreement. A unilateral transfer to a significantly different location — especially one requiring relocation — without consent is constructive dismissal.","ref":"Labour Code · Arts. 20-22","tier":"premium"},
    {"id":40,"q":"What is the employer duty of care for employee health and safety?","a":"Employers have a legal duty to provide a safe working environment, safe equipment, and adequate training for hazardous tasks. They must assess risks, implement safety measures, and report serious workplace accidents. Failure can result in both civil liability and criminal penalties.","ref":"Labour Code · Arts. 77-84","tier":"premium"},
    {"id":41,"q":"Can an employee be dismissed for long-term illness?","a":"Dismissal due to long-term illness is possible but only after allowing a reasonable period for recovery, considering role adjustments, and following proper process. Dismissing an employee immediately upon learning of a serious illness without following due process is unlawful.","ref":"Labour Code · Arts. 68-71","tier":"premium"},
    {"id":42,"q":"What rights does an employee have if falsely accused of misconduct?","a":"An employee falsely accused of misconduct has the right to a fair hearing before any disciplinary sanction is imposed. If the employer proceeds to dismiss without establishing the facts the dismissal is unlawful and the employee can bring a claim before the Ministry of Labour or courts.","ref":"Labour Code · Arts. 38-45","tier":"premium"},
    {"id":43,"q":"Can an employer require employees to work on Fridays?","a":"Friday is the designated weekly rest day in Somalia. Employers may require Friday work only in exceptional circumstances and must provide compensatory rest or additional pay. Systematic rostering of Friday as a regular working day without compensation violates the Labour Code.","ref":"Labour Code · Art. 60","tier":"premium"},
    {"id":44,"q":"Are apprentices and trainees covered by the Labour Code?","a":"Yes. Apprentices and trainees have protections under the Labour Code. Their training agreement must be in writing, they must receive at least the applicable minimum wage, and they cannot be assigned tasks outside the scope of their training.","ref":"Labour Code · Arts. 11-15","tier":"premium"},
    {"id":45,"q":"Can an employer monitor employees communications?","a":"Employers may implement monitoring policies but must inform employees clearly that monitoring takes place. Covert surveillance that invades reasonable privacy is not permitted. Any monitoring policy must be proportionate to the legitimate business need and documented in the contract or staff handbook.","ref":"Labour Code · Arts. 18-20","tier":"premium"},
    {"id":46,"q":"What happens if an employer does not follow safety rules and an accident occurs?","a":"An employer who fails to comply with safety obligations and an employee is injured as a result faces both civil liability — to compensate the injured worker — and potential criminal prosecution. Regulatory authorities can also impose fines and require remedial action.","ref":"Labour Code · Arts. 77-84","tier":"premium"},
    {"id":47,"q":"Can employees be required to wear uniforms or follow a dress code?","a":"Employers can require uniforms or dress codes where there is a legitimate business reason such as safety, hygiene, or professional image. Where uniforms are required the employer should bear the cost. Dress code requirements must be applied consistently and not in a discriminatory manner.","ref":"Labour Code · Arts. 18-20","tier":"premium"},
    {"id":48,"q":"What is the law on annual leave carry-over?","a":"If an employee is unable to take their full annual leave entitlement in a given year due to the demands of their work, they should be allowed to carry the unused leave to the next year. Employers cannot unilaterally cancel accrued unused leave without compensation.","ref":"Labour Code · Arts. 64-67","tier":"premium"},
    {"id":49,"q":"Can an employee be paid in kind rather than cash?","a":"Payment of wages must be made in money. Wages cannot be paid wholly in goods, vouchers, or other non-monetary forms. However legitimate benefits — such as accommodation or transport provided in addition to a cash wage — are permitted as supplementary forms of compensation.","ref":"Labour Code · Arts. 29-30","tier":"premium"},
    {"id":50,"q":"What obligations exist when hiring foreign workers in Somalia?","a":"Employers hiring foreign workers must ensure those workers have valid work permits and comply with immigration requirements. Foreign workers are entitled to the same Labour Code protections as Somali workers once they are lawfully employed. Employing undocumented foreign workers exposes the employer to legal penalties.","ref":"Labour Code · Arts. 3-5","tier":"premium"},
  ],

  "company": [
    {"id":51,"q":"What types of company can I register in Somalia?","a":"The law recognises two main categories. A Private Company can be a simple personal or family business, a limited liability company (LLC), or an unlimited liability company. A Public Company has tradeable share capital and must have more than 50 shareholders.","ref":"Companies Law · Art. 7","tier":"free"},
    {"id":52,"q":"Can one person start a company alone in Somalia?","a":"Yes. A single individual aged 18 or over can found a company. Multiple individuals or other companies can also join together as founders. The minimum age of 18 is a firm requirement — no one under 18 can be a founding member of a registered company.","ref":"Companies Law · Art. 12","tier":"free"},
    {"id":53,"q":"What documents do I need to register a company?","a":"Your founding document must include: the company name; its emblem; its objectives; capital structure and share allocation; the type of business; head office address; full names and contact details of founders; and names and addresses of board members responsible for management.","ref":"Companies Law · Art. 13","tier":"free"},
    {"id":54,"q":"Am I personally liable if my company cannot pay its debts?","a":"It depends on company type. In a limited liability company (LLC), your personal assets are protected — shareholders are not personally responsible for company debts. In an unlimited liability company, personal assets can be used to settle company obligations.","ref":"Companies Law · Arts. 7, 11","tier":"free"},
    {"id":55,"q":"What language does a company name have to be in?","a":"There is no requirement for the name to be in Somali or English. Names can be in Somali, Arabic, English, or any other language including numbers. Abbreviations like Inc, Co, Ltd, and LLC are allowed. The name cannot contain words that violate Somali law.","ref":"Companies Law · Art. 16","tier":"free"},
    {"id":56,"q":"Can a foreign company open a branch in Somalia?","a":"Yes. A foreign company may register a branch in Somalia as soon as it receives a business or work permit. It must follow the same registration process as a domestic company and submit annual reports to the Registrar at the Ministry of Commerce every year.","ref":"Companies Law · Arts. 20, 72, 99","tier":"free"},
    {"id":57,"q":"What happens if a company fails to file its annual report?","a":"The company becomes classified as a delinquent company. This means it loses the right to sue in Somali courts to recover debts or enforce obligations. Persistent non-compliance can lead to forced dissolution, and filing penalties apply from the first missed deadline.","ref":"Companies Law · Arts. 72-75","tier":"free"},
    {"id":58,"q":"As a shareholder can I inspect the company accounts?","a":"Yes. Every shareholder has the right to inspect the company books, decisions, meeting minutes, and tax payment records at any reasonable time. You can request copies and pay for the cost of producing them. You must first state your reason in writing to management.","ref":"Companies Law · Art. 34","tier":"free"},
    {"id":59,"q":"How do you properly close down a company in Somalia?","a":"Voluntary dissolution requires agreement of all shareholders, or when a condition in the founding documents is triggered, or if the company has had no shareholders for 90 days. After dissolution, the company can only conduct winding-up activities: collecting assets, paying debts, and distributing remaining assets to shareholders.","ref":"Companies Law · Arts. 57-60","tier":"free"},
    {"id":60,"q":"Can a dissolved company be brought back to life?","a":"Yes. A dissolved company can be restored to good standing if it meets the founding conditions again. Upon restoration, the law treats the company as if it had never been dissolved — all past debts and obligations of shareholders and managers remain fully enforceable.","ref":"Companies Law · Arts. 78-82","tier":"free"},
    {"id":61,"q":"What is the difference between a private company and a public company?","a":"A private company restricts share transfers, limits membership to 50 shareholders, and cannot offer shares to the public. A public company has freely transferable shares, no maximum shareholder limit, and can raise capital from the public. Private companies become public automatically when they exceed 50 shareholders.","ref":"Companies Law · Art. 8","tier":"premium"},
    {"id":62,"q":"How are decisions made in a company?","a":"Company decisions are made by majority vote of shareholders or by unanimous agreement. Each shareholder vote is weighted according to the value of their shareholding unless the company rules state otherwise. Fundamental changes require a higher threshold — typically a two-thirds majority.","ref":"Companies Law · Art. 27","tier":"premium"},
    {"id":63,"q":"Can a shareholder transfer their shares to anyone?","a":"In a private company, share transfers are restricted and require approval of other shareholders. In a public company, shares can be freely transferred. When a shareholder transfers shares, the new shareholder takes on all rights and obligations of the previous shareholder from the date of transfer.","ref":"Companies Law · Arts. 22-23","tier":"premium"},
    {"id":64,"q":"What happens to shares when a shareholder dies?","a":"When a shareholder dies, their shares pass to their estate and are administered by the legally appointed executor. The executor assumes all rights and obligations of the deceased shareholder. The company cannot hold the estate responsible for more than the value of the shares held.","ref":"Companies Law · Art. 25","tier":"premium"},
    {"id":65,"q":"Can a company sue or be sued in its own name?","a":"Yes. A registered company has full legal personality from the date of registration. It can own property, enter contracts, sue others, and be sued in its own name independently of its shareholders. Shareholders are not personally parties to company lawsuits unless sued individually.","ref":"Companies Law · Art. 6","tier":"premium"},
    {"id":66,"q":"What are the duties of a company manager?","a":"Managers must act in the best interests of the company and shareholders, avoid conflicts of interest, keep company information confidential, and must not compete with the company while managing it. They are liable for losses caused by their negligent or intentionally wrongful acts.","ref":"Companies Law · Arts. 35-40","tier":"premium"},
    {"id":67,"q":"Can a manager borrow money from the company?","a":"A shareholder or manager may borrow from the company or conduct business transactions with it, but such transactions must be conducted on the same commercial terms as with any unrelated third party. Self-dealing that harms the company is a breach of fiduciary duty.","ref":"Companies Law · Art. 38","tier":"premium"},
    {"id":68,"q":"What is required to merge two companies in Somalia?","a":"A merger requires a merger plan approved by at least two-thirds of the shareholders of each company involved. The plan must state the names of the merging companies, terms of the merger, and how shareholder interests will be converted. The merged entity must be registered with the Registrar.","ref":"Companies Law · Arts. 50-54","tier":"premium"},
    {"id":69,"q":"What are the effects of a company merger?","a":"When companies merge, all assets, liabilities, rights, and obligations of the merging companies transfer automatically to the surviving or new company. Shareholders of the merged companies become shareholders of the new entity. The merged companies cease to exist as separate legal entities.","ref":"Companies Law · Art. 54","tier":"premium"},
    {"id":70,"q":"How can a court force a company to close?","a":"A court can order dissolution on application by the Attorney General if fraud is found in founding documents, if the company commits repeated legal violations, or on application by shareholders or creditors if the company is insolvent or has fundamentally failed.","ref":"Companies Law · Art. 62","tier":"premium"},
    {"id":71,"q":"How long does a company registration last?","a":"A company registration does not expire automatically. The company continues to exist until formally dissolved either voluntarily by shareholders or by court order. The company must file annual reports and pay fees to remain in good standing and avoid delinquent status.","ref":"Companies Law · Arts. 66-72","tier":"premium"},
    {"id":72,"q":"Can a company reserve a name before registering?","a":"Yes. Any person can apply to the Registrar to reserve a company name for 90 days. The reservation can be renewed once for another 90 days. During this period no other company can register that name. The reserved name is held for the applicant until they register the company.","ref":"Companies Law · Art. 19","tier":"premium"},
    {"id":73,"q":"Can a company change its name after registration?","a":"Yes. A company can change its name at any time by amending its founding document with shareholder approval and registering the change with the Registrar at the Ministry of Commerce. The old name must be noted as changed in the company registration records.","ref":"Companies Law · Arts. 15-17","tier":"premium"},
    {"id":74,"q":"Can a shareholder bring a lawsuit on behalf of the company?","a":"Yes. A shareholder can bring a derivative action on behalf of the company against a third party or manager who has wronged the company. The shareholder must first request that management take action and wait 30 days unless the urgency of the situation justifies immediate action.","ref":"Companies Law · Arts. 28-33","tier":"premium"},
    {"id":75,"q":"How are profits distributed to shareholders?","a":"Profits are distributed to shareholders in proportion to their shareholding unless founding documents specify otherwise. Profits cannot be distributed if the company has unpaid debts, if doing so would leave it unable to meet obligations, or if a planned investment requires the funds.","ref":"Companies Law · Arts. 43-49","tier":"premium"},
    {"id":76,"q":"Can a shareholder leave a company whenever they want?","a":"Yes. Shareholders may withdraw from a company at any time by giving written notice to management and other shareholders, provided the withdrawal does not violate the company rules or cause damage to the company. If it does cause damage the withdrawing shareholder may be liable for the resulting loss.","ref":"Companies Law · Arts. 45-46","tier":"premium"},
    {"id":77,"q":"What does a shareholder receive when they leave a company?","a":"A withdrawing shareholder is entitled to the cash value of their shares at the time of withdrawal. They also receive any undistributed profits attributable to their shares and reimbursement of expenses incurred on behalf of the company. They cannot demand return of the original asset type contributed.","ref":"Companies Law · Arts. 46-47","tier":"premium"},
    {"id":78,"q":"Can a company operate internationally from Somalia?","a":"Yes. A registered Somali company may conduct business both inside Somalia and abroad. The law explicitly allows domestic companies to trade internationally. For business activities in specific foreign countries the company must comply with those countries local laws and registration requirements.","ref":"Companies Law · Art. 10","tier":"premium"},
    {"id":79,"q":"Can I appeal if the Registrar refuses to register my company?","a":"Yes. If the Registrar refuses to register a company document, the applicant has 45 days to appeal to the Supreme Court of the Federal Republic of Somalia. The appeal must be accompanied by a copy of the refused document and the Registrar reasons for refusal.","ref":"Companies Law · Art. 93","tier":"premium"},
    {"id":80,"q":"Can a company be registered electronically?","a":"Yes. The Registrar may accept company registration documents submitted electronically. Electronic submissions have the same legal effect as paper submissions. The Registrar sets the technical standards for electronic filing and may reject documents that do not meet those standards.","ref":"Companies Law · Art. 83","tier":"premium"},
    {"id":81,"q":"What fees are payable for company registration?","a":"Registration fees are set by the Minister of Commerce by ministerial regulation. The fees cover processing the registration, issuing the certificate, and maintaining the register. Late filing of annual reports attracts additional penalty fees on top of the standard service fee.","ref":"Companies Law · Art. 86","tier":"premium"},
    {"id":82,"q":"What is required to add a new shareholder to an existing company?","a":"Adding a new shareholder requires the approval of at least two-thirds of existing shareholders. The new shareholder details must be recorded in the shareholder register and the change must be reflected in an amendment to the founding documents filed with the Registrar.","ref":"Companies Law · Art. 22","tier":"premium"},
    {"id":83,"q":"Can a foreign company be party to a merger with a Somali company?","a":"Yes. One or more Somali companies can merge with one or more foreign companies. The foreign company must comply with all Somali Companies Law requirements applicable to the merger and must also comply with its own home country laws governing mergers.","ref":"Companies Law · Arts. 50, 55","tier":"premium"},
    {"id":84,"q":"What is the legal effect of a certificate of registration?","a":"A certificate of registration issued by the Registrar is conclusive proof that all legal requirements for registration have been met. It is treated as definitive evidence of the company existence and its details. Courts and third parties are entitled to rely on the certificate contents.","ref":"Companies Law · Arts. 94-95","tier":"premium"},
    {"id":85,"q":"What is the process for a court-appointed administrator or liquidator?","a":"A court hearing a dissolution case can appoint one or more administrators to manage the winding-up process and liquidators to sell assets and pay creditors. The court defines the powers and duties of these appointees and can adjust them as the process proceeds.","ref":"Companies Law · Art. 64","tier":"premium"},
    {"id":86,"q":"Can a company issue different classes of shares?","a":"A company founding document can provide for different classes of shares carrying different rights — such as preference shares with priority dividend rights or different voting rights. The rights attached to each class of share must be clearly stated in the founding document.","ref":"Companies Law · Arts. 7-8","tier":"premium"},
    {"id":87,"q":"Can a company founding document be restated or rewritten?","a":"Yes. A company can restate its founding document at any time by filing a new consolidated version with the Registrar. The restated document supersedes all previous versions and amendments. A restatement can itself include new amendments to the company terms.","ref":"Companies Law · Art. 88","tier":"premium"},
    {"id":88,"q":"What is the liability of managers who exceed their authority?","a":"Managers who act beyond the powers granted to them by the founding document or by shareholders are jointly and personally liable for the losses and obligations arising from those unauthorised acts. The company itself is not bound by unauthorised acts unless it subsequently ratifies them.","ref":"Companies Law · Art. 9","tier":"premium"},
    {"id":89,"q":"What information must appear on company documents and letters?","a":"All official company documents, letters, and invoices must show the registered company name, its registration number, the address of its registered office, and the type of company. Failure to include this information on company documents is a compliance violation.","ref":"Companies Law · Arts. 13-16","tier":"premium"},
    {"id":90,"q":"What happens if incorrect information was included in a company registration?","a":"If incorrect information was submitted during registration it can be corrected by filing a correction document with the Registrar. The correction takes effect from the date the original document was filed. Filing knowingly false information is a criminal offence.","ref":"Companies Law · Arts. 84, 89","tier":"premium"},
    {"id":91,"q":"Can a company act beyond the purposes stated in its founding document?","a":"A company should operate within the purposes stated in its founding document. Managers who cause the company to act beyond those purposes may be personally liable for the consequences. The purposes can be expanded by amending the founding document with shareholder approval.","ref":"Companies Law · Arts. 5, 9","tier":"premium"},
    {"id":92,"q":"Can shareholders agree to resolve disputes through arbitration?","a":"Yes. Shareholders can include an arbitration clause in the founding documents or shareholder agreements, providing that disputes between shareholders or between shareholders and the company will be resolved through arbitration rather than through the courts.","ref":"Companies Law · Arts. 4, 27","tier":"premium"},
    {"id":93,"q":"What records must a company keep and for how long?","a":"Companies must keep founding documents, shareholder registers, minutes of all meetings, financial records, and correspondence with the Registrar. These records must be maintained for the life of the company and for a reasonable period after dissolution so that creditors and authorities can access them.","ref":"Companies Law · Arts. 34, 72","tier":"premium"},
    {"id":94,"q":"What happens when two companies with the same name try to register?","a":"The Registrar will not register a company name that is already in use or so similar to an existing name as to cause confusion. If a name conflict arises the later applicant must choose a different name. The first registered company retains exclusive use of its name.","ref":"Companies Law · Arts. 16-17","tier":"premium"},
    {"id":95,"q":"Can Parliament amend or repeal the Companies Law?","a":"Yes. Parliament has the power to amend any part of, add to, or repeal the Companies Law entirely at any time it considers necessary. All companies operating in Somalia will be subject to any such amendments once they come into force.","ref":"Companies Law · Art. 120","tier":"premium"},
    {"id":96,"q":"What is a delinquent company and what are the consequences?","a":"A delinquent company is one that has failed to pay required fees, file reports, or comply with the Companies Law. A delinquent company cannot bring legal proceedings in Somali courts to collect debts or enforce obligations until it corrects its non-compliance.","ref":"Companies Law · Arts. 73-75","tier":"premium"},
    {"id":97,"q":"What must a company do before distributing profits?","a":"Before distributing profits, all company debts must be paid or provided for, the distribution must not leave the company unable to meet its obligations, all service costs incurred in that period must be paid, and no pre-agreed investment plan requiring those funds must be pending.","ref":"Companies Law · Arts. 48-49","tier":"premium"},
    {"id":98,"q":"Can a company registered in Somalia open offices in other countries?","a":"Yes. A Somali-registered company may expand internationally and open offices in other countries. The company must comply with the local laws and registration requirements of each country it operates in. The Somali Companies Law continues to govern the company internal affairs.","ref":"Companies Law · Art. 10","tier":"premium"},
    {"id":99,"q":"What happens if a company cannot pay its debts for three years?","a":"A manager of a company that has been unable to pay its debts for three or more years and cannot find any other solution may dissolve the company. The manager must notify the Registrar with full details of the financial situation following the prescribed format.","ref":"Companies Law · Art. 67","tier":"premium"},
    {"id":100,"q":"What is the role of the Registrar of Companies?","a":"The Registrar at the Ministry of Commerce maintains the official register of all companies in Somalia. The Registrar reviews and approves registration documents, records all changes to registered companies, issues certificates of registration, and enforces compliance with the Companies Law.","ref":"Companies Law · Arts. 83-98","tier":"premium"},
  ],

  "investment": [
    {"id":101,"q":"Who counts as a foreign investor under Somali law?","a":"Any foreign individual or foreign legal entity — such as a company incorporated outside Somalia — that makes an investment in Somalia in accordance with Somali law qualifies as a foreign investor. Both physical persons and corporations from outside Somalia can seek investment approval.","ref":"Foreign Investment Law · Art. 1(1)","tier":"free"},
    {"id":102,"q":"What forms can a foreign investment take?","a":"Foreign investment can be made in five forms: convertible foreign currency transferred through the Central Bank; machinery and equipment; intellectual property registered in Somalia; funds spent on feasibility studies; and reinvested profits from an earlier approved investment.","ref":"Foreign Investment Law · Art. 2","tier":"free"},
    {"id":103,"q":"Which industries are prioritised for foreign investment?","a":"Priority sectors include agriculture, livestock, fishing, natural resources, manufacturing using local inputs, and tourism where it fits local conditions. Investments that generate foreign exchange, create employment, or introduce new technology are ranked highest for approval.","ref":"Foreign Investment Law · Art. 7","tier":"free"},
    {"id":104,"q":"How do I apply for foreign investment approval?","a":"Complete the Application Form for Approval and Registration at the Foreign Investment Promotion Office at the Ministry of Planning. Submit by registered mail or in person. The Foreign Investment Board must notify you of its decision within 60 days of receiving a complete application.","ref":"Foreign Investment Law · Arts. 8-9","tier":"free"},
    {"id":105,"q":"Can I take my profits out of Somalia freely?","a":"Yes. Profits from a duly registered foreign investment can be freely transferred abroad in freely convertible currency. If you do not transfer all profits in one year, you can carry the remainder forward to any future year. There is no cap on profit repatriation for registered investors.","ref":"Foreign Investment Law · Art. 12","tier":"free"},
    {"id":106,"q":"Can the government seize my investment?","a":"Registered foreign investment is protected from expropriation except in cases of overriding public interest that cannot be addressed by other government measures. If expropriation occurs, the law requires prompt and adequate compensation at fair market value, freely transferable abroad.","ref":"Foreign Investment Law · Art. 18","tier":"free"},
    {"id":107,"q":"How long before I can take my original capital out of Somalia?","a":"You may repatriate a duly registered foreign investment after five years from the date of your original registration certificate. The Board can shorten this period for investments in priority sectors. Repatriation is done in the original currency specified in your certificate.","ref":"Foreign Investment Law · Art. 13","tier":"free"},
    {"id":108,"q":"Do I have to hire Somali staff?","a":"Yes. All companies registered under the Foreign Investment Law must hire qualified Somali nationals whenever available. At least 50% of all staff, contractors, and consultants must be residents of Somalia. Investors are expected to contribute to skills transfer and professional development.","ref":"Foreign Investment Law · Arts. 4(f), 17","tier":"free"},
    {"id":109,"q":"What types of investment are not covered by this law?","a":"The law does not apply to mineral research, mining, petroleum extraction, military manufacturing, weapons storage and disposal, and nuclear power. These sectors are governed by the Mining Code and specific agreements negotiated directly between the Government of Somalia and the interested party.","ref":"Foreign Investment Law · Art. 21","tier":"free"},
    {"id":110,"q":"If there is a dispute with the government how is it resolved?","a":"Disputes are resolved first by mutual agreement, then by bilateral treaties between Somalia and your home country. If neither applies, disputes can be submitted to ICSID international arbitration, or a three-member arbitration panel with the chairman appointed by Somalia Supreme Court President.","ref":"Foreign Investment Law · Art. 19","tier":"free"},
    {"id":111,"q":"What is the Foreign Investment Board and who sits on it?","a":"The Foreign Investment Board is the supreme decision-making body for all foreign investment matters in Somalia. It is chaired by the Director General of the Ministry of Commerce and includes senior officials from Planning, Foreign Affairs, Finance, Labour, the Central Bank, and the Chamber of Commerce.","ref":"Foreign Investment Law · Art. 3","tier":"premium"},
    {"id":112,"q":"What does the Foreign Investment Promotion Office do?","a":"The Promotion Office is the administrative arm supporting the Board. It implements Board decisions, advises foreign investors on application procedures, taxation, and regulations, assists investors through the registration process, and promotes Somalia as a destination for foreign investment.","ref":"Foreign Investment Law · Art. 6","tier":"premium"},
    {"id":113,"q":"How many members are needed for the Board to make a decision?","a":"Seven members of the Foreign Investment Board including the Chairman must be present to form a quorum. Board decisions are made by simple majority vote of members present. At least four members must vote in favour of a decision for it to pass.","ref":"Foreign Investment Law · Art. 5","tier":"premium"},
    {"id":114,"q":"What certificate is issued when an investment is approved?","a":"The Board issues a Certificate of Foreign Investment in an Approved Enterprise to confirm approval. This certificate is valid for 24 months during which the investor must complete the transfer of assets to Somalia as listed in the application.","ref":"Foreign Investment Law · Art. 9","tier":"premium"},
    {"id":115,"q":"What happens if I do not complete my investment within 24 months of approval?","a":"The Certificate of Foreign Investment is valid for 24 months. If the investor has not completed the asset transfer within this period, the Board may grant an extension at the investor request or require a new application to be submitted.","ref":"Foreign Investment Law · Art. 9(4)","tier":"premium"},
    {"id":116,"q":"What certificate is issued when an investment is registered?","a":"Once the investor has transferred the assets to Somalia and the Board is satisfied, it issues a Certificate of Foreign Investment Registered. This certificate confirms the investment is formally registered and the investor can begin enjoying the rights under the law.","ref":"Foreign Investment Law · Art. 10","tier":"premium"},
    {"id":117,"q":"How is the value of non-cash investments determined?","a":"For investments made in machinery, intellectual property, or feasibility studies rather than cash, the Board determines value based on fair market value. The Board may require the investor to produce documentary evidence such as valuations, receipts, or import documents.","ref":"Foreign Investment Law · Art. 10(2)","tier":"premium"},
    {"id":118,"q":"Can I reinvest profits back into my Somali enterprise?","a":"Yes. Profits from a registered investment can be reinvested in the same enterprise or in another enterprise in Somalia. When reinvesting, notify the Board by registered mail. The Board will register the reinvested profit and issue a Certificate of Reinvestment.","ref":"Foreign Investment Law · Art. 11","tier":"premium"},
    {"id":119,"q":"In what currency is my investment registered?","a":"Your investment must be registered in a freely convertible currency as specified by the Central Bank of Somalia. This is the currency recorded in your Certificate of Foreign Investment Registered and used when profits and capital are transferred abroad.","ref":"Foreign Investment Law · Art. 10(3)","tier":"premium"},
    {"id":120,"q":"Can I sell or transfer my foreign investment to someone else?","a":"Yes. You can transfer your foreign investment to another person — either foreign or Somali. If you transfer to a Somali national or entity, the transferee loses the benefits of foreign investor status. Both parties must notify the Board before the transfer takes place.","ref":"Foreign Investment Law · Art. 14","tier":"premium"},
    {"id":121,"q":"Do I need approval to sell my investment to another foreign investor?","a":"No. Transferring your investment to another foreign investor does not require Board approval — only prior notification from both the seller and the buyer is required. This is a simpler process than the original approval and registration procedure.","ref":"Foreign Investment Law · Art. 14(4)","tier":"premium"},
    {"id":122,"q":"What incentives are available to foreign investors?","a":"Foreign investors are eligible for incentives and facilities as provided by applicable legislation. This includes the possibility of long-term land leases of up to 99 years for substantial investments. Specific incentives depend on the sector and size of the investment.","ref":"Foreign Investment Law · Art. 15","tier":"premium"},
    {"id":123,"q":"How much can my company borrow from Somali banks?","a":"An enterprise with a registered foreign investment may borrow from domestic financial institutions up to the limit set by the Central Bank in consultation with the Foreign Investment Board. Proceeds must be used strictly for the activities described in your registration certificate.","ref":"Foreign Investment Law · Art. 16","tier":"premium"},
    {"id":124,"q":"Can my foreign staff get visas to work in Somalia?","a":"Yes. The Board facilitates entry permits and residence visas for foreign personnel employed by a registered enterprise. The Board works with immigration authorities to ensure necessary staff and their families receive the permits needed to live and work in Somalia.","ref":"Foreign Investment Law · Art. 17","tier":"premium"},
    {"id":125,"q":"Are foreign enterprises treated the same as Somali enterprises?","a":"Yes. All enterprises with approved foreign investment must receive treatment as favourable as that given to domestic enterprises. The law establishes a principle of national treatment — foreign investors operating lawfully in Somalia cannot be discriminated against relative to local investors.","ref":"Foreign Investment Law · Art. 18(1)","tier":"premium"},
    {"id":126,"q":"Does my existing investment registered under old laws get any benefit?","a":"Yes. Foreign investments registered under previous Somali investment laws continue to enjoy the rights under those laws. The investor may also opt to benefit from the new law provisions by applying to the Board for re-registration within 180 days of the new law promulgation.","ref":"Foreign Investment Law · Art. 20","tier":"premium"},
    {"id":127,"q":"What are the obligations of banks when dealing with foreign investments?","a":"Banks, public notaries, and entities involved with foreign investment transactions must notify the Foreign Investment Board of significant transactions within 30 days of completion. This includes company formation, domestic borrowing, profit transfers, and repatriation of capital.","ref":"Foreign Investment Law · Art. 22","tier":"premium"},
    {"id":128,"q":"What happens if I do not comply with Somali law as a foreign investor?","a":"Failure to comply with Somali law results in the forfeiture of all benefits provided under the Foreign Investment Law. This means you lose the protections against expropriation, the right to freely transfer profits, and all other privileges that come with registered investor status.","ref":"Foreign Investment Law · Art. 23","tier":"premium"},
    {"id":129,"q":"Can future more favourable laws benefit existing foreign investors?","a":"Yes. The Foreign Investment Law explicitly states that nothing in it prevents investors from benefiting from more favourable provisions enacted in the future. If a subsequent law grants better terms to investors in your sector, you are entitled to those better terms.","ref":"Foreign Investment Law · Art. 24","tier":"premium"},
    {"id":130,"q":"Who has the power to issue regulations under the Foreign Investment Law?","a":"The President of the Federal Republic of Somalia may issue implementing regulations at the proposal of the Foreign Investment Board, having consulted the Minister of National Planning and the Council of Ministers.","ref":"Foreign Investment Law · Art. 25","tier":"premium"},
    {"id":131,"q":"Can I invest in tourism in Somalia?","a":"Yes. Tourism is one of the priority sectors for foreign investment provided the investment harmonises with prevailing social, economic, and infrastructural conditions. Priority tourism investments are eligible for expedited approval and potentially more favourable terms from the Board.","ref":"Foreign Investment Law · Art. 7(2)(f)","tier":"premium"},
    {"id":132,"q":"Can foreign investors invest in agriculture?","a":"Yes. Agriculture is one of the highest-priority sectors for foreign investment in Somalia. Investments that put Somalia agricultural resources to productive use, introduce new technology suited to local conditions, or generate foreign exchange through exports receive highest priority in the approval process.","ref":"Foreign Investment Law · Art. 7","tier":"premium"},
    {"id":133,"q":"What is the role of the Central Bank in foreign investment?","a":"The Central Bank of Somalia specifies the convertible currencies in which investments must be denominated, sets limits on domestic borrowing by registered enterprises, and provides the regulatory framework for currency transfers including profit repatriation.","ref":"Foreign Investment Law · Arts. 2, 10, 16","tier":"premium"},
    {"id":134,"q":"Can I repatriate assets in physical form rather than cash?","a":"Yes. A foreign investor who wishes to repatriate their investment can transfer physical assets — the actual machinery, equipment, or other assets that were the object of the investment — rather than converting them to cash. This is an option available at the investor choice.","ref":"Foreign Investment Law · Art. 13(3)","tier":"premium"},
    {"id":135,"q":"What if the amount I receive when selling my investment exceeds what I invested?","a":"If proceeds from selling or liquidating your investment exceed the original registered investment plus reinvested profits, you are free to transfer the difference abroad in accordance with applicable tax and foreign exchange regulations. The gain is not restricted by the five-year repatriation period.","ref":"Foreign Investment Law · Art. 13(4)","tier":"premium"},
    {"id":136,"q":"Are arbitration decisions in investment disputes final?","a":"Yes. Awards made by an arbitration panel under the Foreign Investment Law are made by majority vote and are final and binding on both parties. They are enforceable in the same way as any final court judgment. There is no further appeal to the Somali courts on the merits.","ref":"Foreign Investment Law · Art. 19(2)","tier":"premium"},
    {"id":137,"q":"Can a foreign company invest in fisheries in Somalia?","a":"Yes. Fishing is an explicitly listed priority sector for foreign investment. Given Somalia extensive coastline and marine resources, fishing investments are strongly encouraged. Such investments receive priority consideration from the Foreign Investment Board and may qualify for the most favourable terms available.","ref":"Foreign Investment Law · Art. 7(2)(c)","tier":"premium"},
    {"id":138,"q":"Can a foreign investor apply to have the five-year lock-in period reduced?","a":"Yes. The Board has discretion to reduce the standard five-year period before repatriation based on the priorities in the investment policy guidelines. Investments in high-priority sectors such as agriculture, fishing, or manufacturing are most likely to qualify for a reduced repatriation waiting period.","ref":"Foreign Investment Law · Art. 13(2)","tier":"premium"},
    {"id":139,"q":"Can I submit my foreign investment application by email?","a":"The application can be submitted by registered mail, delivered in person to the Foreign Investment Promotion Office, or emailed to the Ministry of Planning and International Cooperation with a delivery receipt required. The Office can review the application for completeness before formal submission.","ref":"Foreign Investment Law · Art. 8","tier":"premium"},
    {"id":140,"q":"What technology transfer obligations do foreign investors have?","a":"Foreign investors are expected to make a significant contribution toward transferring technology and managerial know-how to Somalia and upgrading professional skills available in the country. This is a legal expectation and failure to make any effort could affect future investment approvals.","ref":"Foreign Investment Law · Art. 17(3)","tier":"premium"},
    {"id":141,"q":"Can a foreign investor partner with a Somali business?","a":"Yes. Foreign investors can partner with Somali businesses in joint ventures. The Foreign Investment Law does not restrict the ownership structure of joint ventures. The specific rights and obligations of each partner should be governed by a detailed joint venture agreement registered with the relevant authorities.","ref":"Foreign Investment Law · Arts. 1-4","tier":"premium"},
    {"id":142,"q":"Is there a minimum investment amount required?","a":"The Foreign Investment Law does not specify a universal minimum investment amount. The Board evaluates each application on its merits including the nature of the investment, its contribution to Somalia development priorities, and the sector. Larger investments in priority sectors are more likely to receive expedited approval.","ref":"Foreign Investment Law · Arts. 7-9","tier":"premium"},
    {"id":143,"q":"What happens to my investment if I pass away?","a":"If a foreign investor dies, their registered investment forms part of their estate and passes to their heirs according to the applicable inheritance law. The heirs should notify the Foreign Investment Board and may apply to transfer the investment registration into their names subject to Board approval.","ref":"Foreign Investment Law · Arts. 14, 20","tier":"premium"},
    {"id":144,"q":"Can a foreign investor operate in the telecommunications sector?","a":"The Foreign Investment Law does not specifically exclude telecommunications from foreign investment. However telecommunications is typically a regulated sector requiring separate licensing from the relevant communications authority in addition to foreign investment registration. Both approvals are needed to operate lawfully.","ref":"Foreign Investment Law · Arts. 7, 21","tier":"premium"},
    {"id":145,"q":"Does the Foreign Investment Law apply to investments in Somaliland or Puntland?","a":"The Foreign Investment Law applies to the Federal Republic of Somalia. Somaliland administers its own investment regulations separately from the Federal Government. Puntland as a Federal Member State is subject to both Federal law and its own regional regulations. Investors should check applicable rules for each region.","ref":"Foreign Investment Law · Art. 27","tier":"premium"},
    {"id":146,"q":"What reporting obligations do foreign investors have?","a":"Banks, notaries, and entities involved with foreign investments must report significant transactions to the Board within 30 days. Foreign investors themselves should maintain complete records of all investment transactions, employment, and Board correspondence in case of audit or dispute.","ref":"Foreign Investment Law · Art. 22","tier":"premium"},
    {"id":147,"q":"Can a foreign investor bring an employee from their home country?","a":"Yes. The Board facilitates work permits and residence visas for foreign employees of registered enterprises. However all enterprises must ensure that at least 50% of staff are residents of Somalia. Foreign workers must have valid work permits and comply with immigration requirements.","ref":"Foreign Investment Law · Art. 17","tier":"premium"},
    {"id":148,"q":"What is a public-private partnership in the investment context?","a":"The Foreign Investment Law specifically recommends granting land concessions to support youth participation in public-private partnerships. PPPs involve the government and private investors collaborating on infrastructure or service delivery projects, combining public resources with private capital and management expertise.","ref":"Foreign Investment Law · Art. 7(2)(h)","tier":"premium"},
    {"id":149,"q":"Does the Foreign Investment Law override previous investment laws?","a":"Yes. The Foreign Investment Law repeals any previous law that is incompatible with its provisions. From the date of its publication in the Official Bulletin, conflicting provisions of older investment legislation no longer apply.","ref":"Foreign Investment Law · Art. 26","tier":"premium"},
    {"id":150,"q":"How does the Board promote foreign investment in Somalia?","a":"The Foreign Investment Promotion Office working under the Board promotes Somalia as an investment destination. It provides information on investment opportunities, assists investors through the registration process, formulates policy proposals to improve the investment climate, and coordinates with other government institutions.","ref":"Foreign Investment Law · Art. 6","tier":"premium"},
  ],

  "civil": [
    {"id":151,"q":"What is a valid contract under Somali civil law?","a":"A valid contract requires an offer, an acceptance, and something of value exchanged between the parties. Both parties must have legal capacity (be adults of sound mind), and the purpose must be lawful. Contracts whose purpose violates law or public morality are void.","ref":"Somali Civil Code · Arts. 1-30","tier":"free"},
    {"id":152,"q":"Does a contract have to be in writing to be valid?","a":"Not always. Most contracts are valid whether made orally or in writing. However certain important contracts — including those relating to land and employment — must be in writing to be enforceable. Written contracts are always advisable as they provide clear evidence of what was agreed.","ref":"Somali Civil Code · Arts. 15-20","tier":"free"},
    {"id":153,"q":"What is the difference between movable and immovable property in Somalia?","a":"Immovable property refers to land and anything permanently attached to it such as buildings. Movable property is everything else — goods, vehicles, money, and personal belongings. The rules for buying, selling, inheriting, and mortgaging these two types of property differ under Somali civil law.","ref":"Somali Civil Code · Arts. 80-90","tier":"free"},
    {"id":154,"q":"Can a verbal agreement to sell land be enforced?","a":"No. Agreements to sell or transfer land and real property must be in writing to be legally enforceable in Somalia. A verbal agreement to sell land — even if witnessed — does not create a binding legal obligation. Always insist on a written contract for any land transaction.","ref":"Somali Civil Code · Arts. 15-20","tier":"free"},
    {"id":155,"q":"What remedies are available if someone breaches a contract?","a":"The main remedies for breach of contract are: specific performance (court ordering the other party to do what they promised), damages (compensation for losses), and rescission (cancelling the contract). The appropriate remedy depends on the nature of the breach.","ref":"Somali Civil Code · Arts. 190-220","tier":"free"},
    {"id":156,"q":"How long do I have to bring a civil claim in court?","a":"Civil claims are subject to limitation periods. The general limitation period under Somali civil law is typically 10 years from when the cause of action arose, though shorter periods apply to specific types of claims. A claim filed after the limitation period expires will be rejected by the court.","ref":"Somali Civil Code · Arts. 350-380","tier":"free"},
    {"id":157,"q":"What is the law of inheritance in Somalia?","a":"Inheritance in Somalia is governed primarily by Islamic law (Sharia) for Muslims, which distributes the estate among heirs according to fixed shares. Civil law principles supplement Sharia where needed. Non-Muslims may follow different rules applicable to their personal law.","ref":"Somali Civil Code · Arts. 400-450","tier":"free"},
    {"id":158,"q":"Can someone be forced to sell their property?","a":"Generally no. The only exception is compulsory acquisition by the government for a genuine public purpose, which must be accompanied by fair and prompt compensation. Private parties cannot force another person to sell their property.","ref":"Somali Civil Code · Arts. 80-95","tier":"free"},
    {"id":159,"q":"What is a power of attorney and when do I need one?","a":"A power of attorney is a legal document authorising one person to act on behalf of another in specified legal or financial matters. You need one when you cannot be present to sign documents or conduct transactions personally. A power of attorney for land transactions must typically be notarised.","ref":"Somali Civil Code · Arts. 150-165","tier":"free"},
    {"id":160,"q":"What is the legal age of majority in Somalia?","a":"The age of majority — the age at which a person is considered a legal adult with full capacity to enter contracts, sue, and be sued — is 18 years under Somali civil law. Persons under 18 lack full legal capacity and contracts entered into by minors can be voided.","ref":"Somali Civil Code · Arts. 40-55","tier":"free"},
    {"id":161,"q":"Can a contract signed under duress or fraud be cancelled?","a":"Yes. A contract obtained through duress, fraud, or misrepresentation can be declared voidable at the request of the affected party. The affected party must act promptly to void the contract once the duress or fraud is discovered.","ref":"Somali Civil Code · Arts. 60-75","tier":"premium"},
    {"id":162,"q":"What is a guarantee or surety agreement?","a":"A guarantee is a contract in which a third party — the guarantor — promises to pay a debt or perform an obligation if the primary debtor fails to do so. The guarantor is only liable if the debtor actually defaults. A guarantee must generally be in writing to be enforceable.","ref":"Somali Civil Code · Arts. 280-300","tier":"premium"},
    {"id":163,"q":"What rights does a tenant have in Somalia?","a":"A tenant has the right to peaceful enjoyment of the rented property, to have essential repairs made by the landlord, and to receive proper notice before the tenancy is terminated. The landlord cannot enter the property without permission or evict the tenant without following proper legal process.","ref":"Somali Civil Code · Arts. 320-345","tier":"premium"},
    {"id":164,"q":"Can a landlord increase rent during a fixed-term lease?","a":"During a fixed-term lease, the rent is fixed and cannot be increased unilaterally by the landlord before the lease expires. Rent increases require either the agreement of the tenant or the expiry of the current lease term. Any agreed rent increase should be documented in writing.","ref":"Somali Civil Code · Arts. 320-345","tier":"premium"},
    {"id":165,"q":"What notice must a landlord give before evicting a tenant?","a":"A landlord must give reasonable written notice before ending a tenancy or initiating eviction proceedings. Eviction without proper notice or through physical force is unlawful regardless of whether the tenant owes rent. The required notice period depends on the type of tenancy and reason for termination.","ref":"Somali Civil Code · Arts. 320-345","tier":"premium"},
    {"id":166,"q":"What is a mortgage and how does it work?","a":"A mortgage is a legal arrangement in which property is used as security for a loan. If the borrower fails to repay, the lender has the right to take and sell the property to recover the debt. The mortgage must be in writing and registered to be valid against third parties.","ref":"Somali Civil Code · Arts. 250-280","tier":"premium"},
    {"id":167,"q":"Can I use land as collateral for a loan?","a":"Yes. Land and immovable property can be pledged as collateral through a mortgage arrangement. The mortgage must be executed in writing and registered with the appropriate authority. Once registered it takes priority over later claims on the property. The landowner retains possession while the mortgage is in force.","ref":"Somali Civil Code · Arts. 250-280","tier":"premium"},
    {"id":168,"q":"What is unjust enrichment under civil law?","a":"Unjust enrichment occurs when one person gains a benefit at the expense of another without a legal justification. Somali civil law allows the person who suffered the loss to reclaim the value of the benefit from the person who was enriched, even without a contract between them.","ref":"Somali Civil Code · Arts. 225-240","tier":"premium"},
    {"id":169,"q":"What is a tort and what compensation is available?","a":"A tort is a civil wrong — an act or omission that causes harm to another person, giving that person the right to sue for compensation. Common torts include negligence, trespass, and defamation. The compensation recoverable is the actual loss suffered as a result of the wrongful act.","ref":"Somali Civil Code · Arts. 190-225","tier":"premium"},
    {"id":170,"q":"What is the difference between a void and a voidable contract?","a":"A void contract has no legal effect from the start — it is treated as if it never existed. A voidable contract is initially valid but can be cancelled by one of the parties who was misled, pressured, or lacked capacity. Until actually cancelled, a voidable contract remains in force.","ref":"Somali Civil Code · Arts. 56-75","tier":"premium"},
    {"id":171,"q":"What is meant by force majeure in a contract?","a":"Force majeure refers to extraordinary events beyond a party control — such as natural disasters, wars, or government actions — that make it impossible to perform a contractual obligation. If such an event occurs, the affected party may be excused from performance without being liable for breach.","ref":"Somali Civil Code · Arts. 195-205","tier":"premium"},
    {"id":172,"q":"Can I transfer my contractual rights to a third party?","a":"Yes. A party to a contract can generally assign their contractual rights to a third party — this is called an assignment. However you cannot assign personal obligations without the other party consent. The other party should be notified of any assignment.","ref":"Somali Civil Code · Arts. 170-185","tier":"premium"},
    {"id":173,"q":"How is co-owned property managed in Somalia?","a":"When property is co-owned by two or more persons, decisions about its management, use, and maintenance must generally be made by majority agreement based on ownership shares. Any co-owner can request division of the property through the courts if co-owners cannot agree.","ref":"Somali Civil Code · Arts. 95-115","tier":"premium"},
    {"id":174,"q":"Can I give property as a gift and can it be taken back?","a":"Property can be given as a genuine gift and the gift is generally irrevocable once made and accepted. However a gift can be revoked in exceptional circumstances such as serious ingratitude by the recipient. Gifts of land must be documented in writing.","ref":"Somali Civil Code · Arts. 310-320","tier":"premium"},
    {"id":175,"q":"What is a usufruct right?","a":"A usufruct is the right to use and enjoy the fruits of property owned by another person, without owning the property itself. The usufructuary can use the property and collect any income it generates but cannot sell or permanently alter it. Usufructs are often created by inheritance or contract.","ref":"Somali Civil Code · Arts. 115-135","tier":"premium"},
    {"id":176,"q":"Can a debt be transferred to someone else?","a":"Yes. A debt can be transferred from the original debtor to a new debtor through novation, which requires the creditor consent. Alternatively a creditor can assign their right to collect a debt to a third party without needing the debtor consent, though the debtor must be notified.","ref":"Somali Civil Code · Arts. 170-190","tier":"premium"},
    {"id":177,"q":"What is the legal process for collecting a debt in Somalia?","a":"A creditor seeking to collect an unpaid debt should first make written demand to the debtor. If payment is not made, the creditor can file a civil claim before the competent court. If the court issues a judgment in the creditor favour, enforcement measures including seizure of assets can be taken against the debtor.","ref":"Somali Civil Code · Arts. 190-225","tier":"premium"},
    {"id":178,"q":"What share of inheritance does a wife receive?","a":"Under Islamic inheritance rules as applied in Somalia, a wife receives one-quarter of the estate if there are no children, and one-eighth if there are children. If there are multiple wives they share the applicable fraction equally. The husband estate is then divided among other heirs after the wife share is set aside.","ref":"Somali Civil Code · Arts. 400-450","tier":"premium"},
    {"id":179,"q":"What share of an inheritance does a daughter receive?","a":"Under Islamic inheritance rules, a daughter receives half the share of a son. If there are only daughters and no sons, daughters together receive two-thirds of the estate if there are two or more daughters, or one-half if there is only one daughter.","ref":"Somali Civil Code · Arts. 400-450","tier":"premium"},
    {"id":180,"q":"Can a person be disinherited under Somali law?","a":"Under Islamic inheritance principles, certain close relatives including spouses, children, and parents have fixed entitlements that cannot be removed by the deceased wishes. A person cannot write a relative out of their will if that relative is a legal heir entitled to a fixed share.","ref":"Somali Civil Code · Arts. 400-450","tier":"premium"},
    {"id":181,"q":"What happens to property if someone dies without a will?","a":"If a person dies intestate (without a valid will), their estate is distributed according to Islamic inheritance law as applied in Somalia. The estate passes to legal heirs in proportions prescribed by Sharia. There is no concept of the estate passing to the state if any legal heirs exist.","ref":"Somali Civil Code · Arts. 400-450","tier":"premium"},
    {"id":182,"q":"Can foreigners own land in Somalia?","a":"Foreign nationals face restrictions on owning land in Somalia. Land ownership is generally reserved for Somali citizens. Foreigners may access land through long-term leases — up to 99 years for significant investments under the Foreign Investment Law — but outright ownership by foreigners is not generally permitted.","ref":"Somali Civil Code · Arts. 80-95","tier":"premium"},
    {"id":183,"q":"Can a contract be made on behalf of someone who has not authorised it?","a":"Generally no. A person can only create binding obligations on behalf of another if they have been given authority to do so by a power of attorney or by implication from the circumstances. However if the unauthorised party later ratifies the contract it becomes binding from the date originally made.","ref":"Somali Civil Code · Arts. 150-170","tier":"premium"},
    {"id":184,"q":"What is the difference between a loan and a gift?","a":"A loan creates an obligation to repay — the recipient must return the money or property at an agreed time or on demand. A gift transfers ownership permanently with no obligation to repay. A loan creates a debt enforceable through the courts while a gift generally does not.","ref":"Somali Civil Code · Arts. 300-320","tier":"premium"},
    {"id":185,"q":"Can a landlord keep a security deposit if the tenant causes no damage?","a":"No. A security deposit is held as security for damage beyond normal wear and tear. If the tenant leaves the property in good condition, the landlord must return the deposit in full. Unjustified retention of a deposit is a breach of contract and the tenant can pursue recovery through the courts.","ref":"Somali Civil Code · Arts. 320-345","tier":"premium"},
    {"id":186,"q":"What is a notarial deed and when is it required?","a":"A notarial deed is a legal document prepared and certified by a notary public. It provides the highest level of evidentiary reliability. Notarial deeds are required for certain high-importance transactions including transfer of real property, creation of mortgages, and powers of attorney for property matters.","ref":"Somali Civil Code · Arts. 15-20","tier":"premium"},
    {"id":187,"q":"What is the principle of good faith in contracts?","a":"Good faith is a fundamental principle requiring parties to deal honestly and fairly with each other during both the negotiation and performance of a contract. A party who deliberately misleads the other, conceals important information, or performs obligations in bad faith may be liable for any resulting loss.","ref":"Somali Civil Code · Arts. 1-30","tier":"premium"},
    {"id":188,"q":"Can I include a penalty clause in a contract?","a":"Yes. A penalty clause specifying a fixed amount payable if a party breaches the contract is permitted under Somali civil law. Such clauses provide certainty and avoid the need to prove actual loss. However courts may reduce an excessively punitive penalty clause to a reasonable amount if challenged.","ref":"Somali Civil Code · Arts. 190-220","tier":"premium"},
    {"id":189,"q":"What is the rule about contracts that are impossible to perform?","a":"A contract to do something that is objectively impossible from the outset is void. If performance becomes impossible after the contract is made due to circumstances beyond either party control (force majeure), both parties are generally excused from performance without liability.","ref":"Somali Civil Code · Arts. 195-205","tier":"premium"},
    {"id":190,"q":"What protection does a buyer have against hidden defects in purchased goods?","a":"A seller is liable for hidden defects in goods that make them unfit for their intended purpose or significantly reduce their value, provided the buyer did not know of the defect at the time of purchase. The buyer can claim a price reduction or cancellation of the sale and return of the purchase price.","ref":"Somali Civil Code · Arts. 130-150","tier":"premium"},
    {"id":191,"q":"Can I claim compensation if someone damages my property?","a":"Yes. A person who wrongfully or negligently damages another property is liable to compensate the owner for the loss. The compensation should put the owner in the same financial position as if the damage had not occurred — covering repair costs, loss of use, and any reduction in the property value.","ref":"Somali Civil Code · Arts. 190-225","tier":"premium"},
    {"id":192,"q":"What happens if a party to a contract dies before it is performed?","a":"When a party to a contract dies, contractual rights and obligations generally pass to their heirs or estate. The heirs inherit the benefit and burden of existing contracts. However purely personal contracts depending on the specific skills or identity of the deceased terminate on death.","ref":"Somali Civil Code · Arts. 170-190","tier":"premium"},
    {"id":193,"q":"Is mediation available as an alternative to court for civil disputes?","a":"Yes. Parties to a civil dispute can agree to resolve their disagreement through mediation — a structured negotiation facilitated by a neutral third party. Mediation is faster, cheaper, and more private than court proceedings. An agreement reached through mediation can be made legally binding.","ref":"Somali Civil Code · Arts. 1-30","tier":"premium"},
    {"id":194,"q":"Can a contract be partly enforced if only some terms are unlawful?","a":"Yes. If only certain terms of a contract are unlawful the court can sever those terms and enforce the rest, provided the remaining terms make sense and represent what the parties would have agreed without the unlawful provisions.","ref":"Somali Civil Code · Arts. 56-75","tier":"premium"},
    {"id":195,"q":"Can I sell property that I do not yet own?","a":"A contract for the sale of property not yet owned by the seller — known as a future sale — can be valid provided the seller acquires ownership before the agreed delivery date and transfers it to the buyer. If the seller fails to do so, they are liable to the buyer for breach of contract.","ref":"Somali Civil Code · Arts. 130-150","tier":"premium"},
    {"id":196,"q":"What is a lien and how does it protect a creditor?","a":"A lien is the right of a creditor to retain possession of property belonging to the debtor until the debt is paid. For example, a mechanic may retain a repaired vehicle until the repair bill is paid. A lien provides security by right of possession without requiring a formal mortgage.","ref":"Somali Civil Code · Arts. 250-280","tier":"premium"},
    {"id":197,"q":"What happens to my property in Somalia when I move abroad?","a":"Moving abroad does not automatically affect your ownership of property in Somalia. You remain the legal owner and can manage the property through an authorised representative using a power of attorney. Property taxes and maintenance obligations continue to apply regardless of where you reside.","ref":"Somali Civil Code · Arts. 80-95","tier":"premium"},
    {"id":198,"q":"Can a court order someone to do something rather than just pay compensation?","a":"Yes. Courts can issue orders for specific performance — requiring a party to fulfil their contractual obligations — rather than simply awarding monetary compensation. Specific performance is typically ordered where monetary compensation would not adequately remedy the breach such as in unique property transactions.","ref":"Somali Civil Code · Arts. 190-220","tier":"premium"},
    {"id":199,"q":"What is adverse possession and does it apply in Somalia?","a":"Adverse possession is the principle by which a person who occupies and uses land openly and continuously for a long period without the owner permission may acquire legal ownership. Civil law systems including Somalia recognise the concept of acquisitive prescription through long-term possession.","ref":"Somali Civil Code · Arts. 350-380","tier":"premium"},
    {"id":200,"q":"Can a minor enter into a contract in Somalia?","a":"Persons under 18 lack full legal capacity in Somalia. Contracts entered into by minors are generally voidable at the minor request or at the request of their legal guardian. Certain basic transactions necessary for daily life may be treated as valid. Parents or guardians are responsible for the legal affairs of minors.","ref":"Somali Civil Code · Arts. 40-55","tier":"premium"},
  ],
}

@app.route('/')
def index():
    return send_from_directory('static', 'index.html')

@app.route('/<path:path>')
def static_files(path):
    try:
        return send_from_directory('static', path)
    except:
        return send_from_directory('static', 'index.html')

@app.route('/api/qa')
def get_qa():
    area = request.args.get('area', 'all')
    if area == 'all':
        result = []
        for a, items in QA_DATA.items():
            for item in items:
                result.append({**item, 'area': a})
    else:
        result = [{**item, 'area': area} for item in QA_DATA.get(area, [])]
    return jsonify(result)

@app.route('/api/ask', methods=['POST'])
def ask():
    import requests as req
    data = request.get_json()
    question = data.get('question', '').strip()
    law_area = data.get('lawArea', 'General')

    if not question:
        return jsonify({'error': 'Question is required'}), 400

    if not ANTHROPIC_API_KEY:
        return jsonify({'error': 'API key not configured. Set ANTHROPIC_API_KEY environment variable.'}), 500

    payload = {
        'model': 'claude-haiku-4-5-20251001',
        'max_tokens': 600,
        'system': SYSTEM_PROMPT,
        'messages': [{'role': 'user', 'content': 'Law area: ' + law_area + ' Question: ' + question}]
    }

    headers = {
        'x-api-key': ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json'
    }

    try:
        resp = req.post(
            'https://api.anthropic.com/v1/messages',
            headers=headers,
            json=payload,
            timeout=30
        )

        if resp.status_code != 200:
            try:
                error_body = resp.json()
                error_msg = error_body.get('error', {}).get('message', 'Unknown error')
            except:
                error_msg = resp.text
            return jsonify({'error': 'Anthropic error: ' + error_msg}), 500

        result = resp.json()
        answer = result['content'][0]['text']
        return jsonify({'answer': answer, 'question': question})

    except req.exceptions.Timeout:
        return jsonify({'error': 'Request timed out. Please try again.'}), 504
    except Exception as e:
        return jsonify({'error': 'Server error: ' + str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(debug=False, host='0.0.0.0', port=port)